### ISSUE TITLE
Arm64 release for `ext-alpine`

### ISSUE THREAD

**Issue by jrauschenbusch** [floryn90/docker-hugo#117]
**Is your feature request related to a problem? Please describe.**
Currently there is not Docker Hub Image for Arm64 and `ext-alpine` images.

**Describe the solution you'd like**
Arm64 `ext-alpine`, `ext-asciidoctor`, ...

**Describe alternatives you've considered**
`ext-debian`. But huge image which takes really long to load.

**Comment by floryn90** [comment]
hi @jrauschenbusch,
Thanks for the suggestion! The support for arm64 has been included also for alpine ext images! 

Until there will be a new Hugo release, you can use the edge tags that brings the latest hugo version - 0.127.0

Please let me know if there are some issues with the arm64 images!
