### ISSUE TITLE
0.136.2 yields permission errors

### ISSUE THREAD

**Issue by schwartzman** [floryn90/docker-hugo#163]
**Describe the bug**
Running on Github Actions, 0.136.2 yields permission errors.
Any filesystem action resulting from the command `hugo` fails, with a "permission denied" error.

**To Reproduce**
Upgrade from 0.136.1 to 0.136.2

**Comment by floryn90** [comment]
hi @schwartzman,

Could you please specify exactly the tag that you're using ?

**Comment by rojomisin** [comment]
@floryn90 in `hugo:1.38.0-ext-alpine-onbuild` still getting 
```
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended linux/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=gohugoio

WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
WARN  Failed to write jsconfig.json: open /src/assets/jsconfig.json: permission denied
Total in 1265 ms
Error: error building site: mkdir /src/resources/_gen/assets/sass: permission denied
The command '/bin/sh -c if [ -e "$ONBUILD_SCRIPT_VALUE" ]; then exec sh $ONBUILD_SCRIPT_VALUE; else exec hugo $HUGO_CMD; fi' returned a non-zero code: 1
Error: Process completed with exit code 1.
```

**Comment by schwartzman** [comment]
> Could you please specify exactly the tag that you're using ?

Hey, sorry for the slow response on this.

We use the `ext-ubuntu-ci` flavor.

Have just tested `0.136.5` and `0.137.1` in our deployment pipeline and the initial permissions error is present with both.

Reverting to `0.136.1-ext-ubuntu-ci` yields expected behavior.

**Comment by floryn90** [comment]
> > Could you please specify exactly the tag that you're using ?
> 
> Hey, sorry for the slow response on this.
> 
> We use the `ext-ubuntu-ci` flavor.
> 
> Have just tested `0.136.5` and `0.137.1` in our deployment pipeline and the initial permissions error is present with both.
> 
> Reverting to `0.136.1-ext-ubuntu-ci` yields expected behavior.

Could you please try to use the latest image: 0.138.0 and let me know?

**Comment by schwartzman** [comment]
Same problem persists with 0.138.0.

(Is there a reason this issue has been marked closed when it remains so completely unresolved?)

**Comment by floryn90** [comment]
> @floryn90 in `hugo:1.38.0-ext-alpine-onbuild` still getting
> 
> ```
> hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended linux/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=gohugoio
> 
> WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
> WARN  Failed to write jsconfig.json: open /src/assets/jsconfig.json: permission denied
> Total in 1265 ms
> Error: error building site: mkdir /src/resources/_gen/assets/sass: permission denied
> The command '/bin/sh -c if [ -e "$ONBUILD_SCRIPT_VALUE" ]; then exec sh $ONBUILD_SCRIPT_VALUE; else exec hugo $HUGO_CMD; fi' returned a non-zero code: 1
> Error: Process completed with exit code 1.
> ```

could you please provide more details? 
I just checked to build my website using the ext-alpine-onbuild image and it worked fine without specifying any user, just using the default hugo user.

**Comment by floryn90** [comment]
> Same problem persists with 0.138.0.
> 
> (Is there a reason this issue has been marked closed when it remains so completely unresolved?)

Yesterday I built new docker images with Hugo version 0.138.0 where I put a fix regarding the permission issue. Could you please try with latest 0.138.0 images and let me know if the issue persist?

**Comment by schwartzman** [comment]
Thank you for the persistent effort on this!

Unfortunately…

> Error: error building site: failed to acquire a build lock: open /github/workspace/.hugo_build.lock: permission denied

**Comment by floryn90** [comment]
> Thank you for the persistent effort on this!
> 
> Unfortunately, the latest version of 0.138.0 still yields:
> 
> > Error: error building site: failed to acquire a build lock: open /github/workspace/.hugo_build.lock: permission denied

That is not an internal image path! It seems to be a path into the GitHub runner!

**Comment by schwartzman** [comment]
It does seem that way. With version 0.138.0, if I run the hugo build step with `--noBuildLock` the following errors are returned:

> ERROR Failed to publish Resource: mkdir /github/workspace/public: permission denied
> ERROR mkdir /github/workspace/public: permission denied
> Error: error copying static files: mkdir /github/workspace/public: permission denied

**Comment by floryn90** [comment]
> It does seem that way. With version 0.138.0, if I run the hugo build step with `--noBuildLock` the following errors are returned:
> 
> > ERROR Failed to publish Resource: mkdir /github/workspace/public: permission denied
> > ERROR mkdir /github/workspace/public: permission denied
> > Error: error copying static files: mkdir /github/workspace/public: permission denied

Going to close this issue since it’s not related to builder image of Hugo but to GitHub runner setup or your GitHub action workflow configuration

**Comment by schwartzman** [comment]
Such a shame, anotyher Hugo Docker repo goes the way of klakegg…

For anyone else dealing with this or similar issues, we've switched over to https://github.com/hugomods/docker, which actually works.

**Comment by gravelld** [comment]
I see the similar (permissions related) thing with a run that doesn't use GitHub runners or actions, just a plain Docker build of a Dockerfile that is dependent on `ext-debian-onbuild`:

```
$ docker build -t website:20250410 -f website.Dockerfile .
...
Step 1/12 : ARG HUGO_DIR=/src/website/
Step 2/12 : ARG HUGO_ENV_ARG=production
Step 3/12 : FROM floryn90/hugo:0.145.0-ext-debian-onbuild AS website_builder
...
Start building sites … 
hugo v0.145.0-666444f0a52132f9fec9f71cf25b441cc6a4f355+extended linux/amd64 BuildDate=2025-02-26T15:41:25Z VendorInfo=gohugoio

Total in 2016 ms
Error: error building site: failed to acquire a build lock: open /src/website/.hugo_build.lock: permission denied
The command '/bin/sh -c if [ -e "$ONBUILD_SCRIPT_VALUE" ]; then exec sh $ONBUILD_SCRIPT_VALUE; else exec hugo $HUGO_CMD; fi' returned a non-zero code: 1
```
The same thing happens with `0.136.1-ext-debian-onbuild`.

It works with `131.0-ext-debian-onbuild`.

I think this is discussed in #174 where the solution of using the root user to build was proposed. This works for a CI environment, but if run in a long-lived dev environment won't this mash up the file ownership somewhat?

**Comment by floryn90** [comment]
> The Dockerfile happens to be in the parent folder to the website, and that's consistent with the rest of our product, so I thought I could just parameterise it using `HUGO_DIR`.

It doesn't matter because the output of Hugo will be placed into /target directory and it will not include your dockerfile.

This is the docherfile for on build images: [onbuild.df](src/docker/_imports/onbuild.df)
