### ISSUE TITLE
Permission issues with latest version

### ISSUE THREAD

**Issue by horihel** [floryn90/docker-hugo#174]
**Describe the bug**
Latest version of the ext-ci container can no longer be used as container resource in Azure pipelines.

It looks like azure agent expects to be able to create groups and users

**To Reproduce**
1. create a container job (job.job.container) with ext-ci latest as container image
2. pipeline will fail during container setup

log shows

```sh
/usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 bash -c "getent passwd 1001 | cut -d: -f1 "
/usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 bash -c "if [[ -e '/etc/alpine-release' ]]; then echo 'Alpine-based image detected.'; fi"
/usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 groupadd -g 127 docker_azpcontainer
/usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 useradd -m -u 1001 vsts_azpcontainer
##[error]Docker-exec executed: `useradd -m -u 1001 vsts_azpcontainer`; container id: `d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5`; exit code: `1`; command output: `useradd: Permission denied.`, `useradd: cannot lock /etc/passwd; try again later.`

```

**Expected behavior**
azure agent sets up its users and continues running like it did with previous iterations

workaround is to set options: --user root

This might be related to #172

**Comment by floryn90** [comment]
> **Describe the bug** Latest version of the ext-ci container can no longer be used as container resource in Azure pipelines.
> 
> It looks like azure agent expects to be able to create groups and users
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. create a container job (job.job.container) with ext-ci latest as container image
> 2. pipeline will fail during container setup
> 
> log shows
> 
> ```shell
> /usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 bash -c "getent passwd 1001 | cut -d: -f1 "
> /usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 bash -c "if [[ -e '/etc/alpine-release' ]]; then echo 'Alpine-based image detected.'; fi"
> /usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 groupadd -g 127 docker_azpcontainer
> /usr/bin/docker exec  d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5 useradd -m -u 1001 vsts_azpcontainer
> ##[error]Docker-exec executed: `useradd -m -u 1001 vsts_azpcontainer`; container id: `d8a918305a996cf5c8cf819fb836050128bfea195eb943e1e82f8bcec79d01a5`; exit code: `1`; command output: `useradd: Permission denied.`, `useradd: cannot lock /etc/passwd; try again later.`
> ```
> 
> **Expected behavior** azure agent sets up its users and continues running like it did with previous iterations
> 
> workaround is to set options: --user root
> 
> This might be related to #172

Please try to specify the root as user into your pipeline!

**Comment by rojomisin** [comment]
dockerhub shows another sha
https://hub.docker.com/layers/floryn90/hugo/0.138.0-ext-alpine-onbuild/images/sha256-3d0d22acb1c2d85da1da344de9b6418f2994444b4f87cdde092c9dffacfad8db?context=explore

can you release a 0.138.1 patch version perhaps 🙏

**Comment by horihel** [comment]
> > workaround is to set options: --user root
> > This might be related to #172
> 
> Please try to specify the root as user into your pipeline!

Thanks - just to clear things up - is this going to be the solution going forward?

I'm just asking because we'll have to adjust quite a few pipelines to make them work again after the changes from #172

**Comment by floryn90** [comment]
> > > workaround is to set options: --user root
> > > This might be related to #172
> > 
> > 
> > Please try to specify the root as user into your pipeline!
> 
> Thanks - just to clear things up - is this going to be the solution going forward?
> 
> I'm just asking because we'll have to adjust quite a few pipelines to make them work again after the changes from #172

Hi @horihel, 
Yes, for security reasons, there is no more image with default root user but it’s present inside the image. The default user is hugo which has the permissions to write inside /src and /target

**Comment by horihel** [comment]
thank you for clarifying
