### ISSUE TITLE
SASS version is too old for Hugo 0.139.0

### ISSUE THREAD

**Issue by robinwhittleton** [floryn90/docker-hugo#178]
We currently set SASS 1.62.1: https://github.com/floryn90/docker-hugo/blob/966786837fecfca04bc975edaf204b36fb366ca0/src/files/_script/sass-embedded.sh#L9

As of Hugo 0.139.0, SASS version 1.63.0+ is needed: https://github.com/gohugoio/hugo/issues/13065

Can this be bumped? SASS 1.81.0 is the current latest.

**Comment by floryn90** [comment]
This issue should be fixed with latest images! Please be advised that sass is available only into ext-ubuntu(-ci|-onbuild) and ext-debian(-ci|-onbuild) images

```shell
docker run -it --rm --entrypoint /bin/bash floryn90/hugo:ext-ubuntu
hugo@f7fa69bad55a:/src$ sass --version
1.81.0
hugo@f7fa69bad55a:/src$ dart-sass-embedded --version
{
  "protocolVersion": "3.1.0",
  "compilerVersion": "1.81.0",
  "implementationVersion": "1.81.0",
  "implementationName": "dart-sass",
  "id": 0
}
```
