### ISSUE TITLE
Publish the GitHub actions

### ISSUE THREAD

**Issue by MarkEWaite** [floryn90/docker-hugo#65]
The [status page for Jenkins project infrastructure](https://status.jenkins.io/) is a happy consumer of the docker-hugo container.  Thanks so much for maintaining it and for releasing new versions.

We've used the GitHub actions that were published from the [original repository](https://github.com/klakegg/docker-hugo/issues/87).  Unfortunately, those actions don't seem to know about the new releases.

Would you be willing to publish the GitHub actions so that we can switch to use them from your repository instead of using them from the original?  Example of our use is in the [hugo actions definition](https://github.com/jenkins-infra/status/blob/main/.github/workflows/hugo.yaml) in the [status repository](https://github.com/jenkins-infra/status/).

**Comment by floryn90** [comment]
hi @MarkEWaite, 
just published the first version of the action here: https://github.com/marketplace/actions/powerful-hugo-action

It's exactly as the @klakegg version but I updated the references to point on the docker hugo releases from my repository.

**Comment by MarkEWaite** [comment]
Thanks very much!
