### ISSUE TITLE
[Feature Req] Add container with go installed

### ISSUE THREAD

**Issue by shruuub** [floryn90/docker-hugo#95]
Hi,
It might be niche, but since I suppose there are quite a few users using Hugo modules, it might make sense to add an alpine container with go preinstalled. I don't really understand the project's structure, otherwise I'd do a PR myself.
Thanks :)

**Comment by floryn90** [comment]
Hi @shruuub,
The ext images has already the go included into images! Please make a try and let me know if it’s working or not!

**Comment by shruuub** [comment]
> Hi @shruuub, The ext images has already the go included into images! Please make a try and let me know if it’s working or not!

Nice! I did forget to test those. Will do so later.

**Comment by floryn90** [comment]
Closing this issue since the go executable is present into ext images

**Comment by shruuub** [comment]
Right, wanted to comment and close, my bad, sorry.
